## What is a Vector?
- A vector is an arrow in space with a specific direction and length, often representing a piece of data. It is the central building block of linear algebra, including matrices and linear transformations. The purpose of a vector is to visually represent a piece of data.  We declare a vector mathematically like this:

$ \vec{v} \quad = \quad \begin{bmatrix} x \\ y \end{bmatrix}$

$ \vec{v} \quad = \quad \begin{bmatrix} 3 \\ 2 \end{bmatrix}$ 

we can declare a vector using a list or a numpy array:

In [1]:
v = [3,2]
print(v)

[3, 2]


In [2]:
import numpy as np
v = np.array([3,2])
print(v)

[3 2]


Vectors can exist on more than two dimensions, next we declare a three-dimensional vector along axes x, y, and z:

$ \vec{v} \quad = \quad \begin{bmatrix} x \\ y  \\ z \end{bmatrix} \quad = \quad \begin{bmatrix} 4 \\ 1  \\ 2 \end{bmatrix}$

Expressed using numpy:


In [4]:
v = np.array([4, 1, 2])
print(v)

[4 1 2]


In [5]:
# 5D vector
v = np.array([1, 2, 3, 4, 5])
print(v)

[1 2 3 4 5]


### adding and combining vectors

say we have two vectors $\vec{v}$ and $\vec{w}$. How do we add those two vectors together?

$\vec{v} \quad = \quad \begin{bmatrix} 3 \\ 2 \end{bmatrix}$

$\vec{w} \quad = \quad \begin{bmatrix} 2 \\ -1 \end{bmatrix}$

$\vec{v} + \vec{w} \quad = \quad \begin{bmatrix} 3 + 2 \\ 2 + -1 \end{bmatrix} \quad = \quad \begin{bmatrix} 5 \\ 1 \end{bmatrix}$

In [6]:
from numpy import array
v = array([3,2])
w = array([2, -1])

v_plus_w = v + w
print(v_plus_w)

[5 1]


## Scaling Vectors

*Scaling* is growing or shrinking a vectors length.  You can grow/shrink a vector by multiplying or scaling it with a single value, known as a *scalar*.  

In [7]:
v = array([3, 1])
scaled_v  = 2 * v
print(scaled_v)

[6 2]


Scaling a vector does not change its direction, only its magnitude. When you multiply a vector by a negative number it flips the direction of the vector. 

## Span and Linear Dependence

With these two operations (adding and scaling vectors), we can combine two vectors and scale them to create any resulting vector that we want.
- The whole space of possible vectors is called *span*. and in most cases our span can create unlimited vectors off those two vectors, simply by scaling and summing them.
- When we have two vectors in two different directions,  they are *linearly independent* and have this unlimited span.

But what happens when we are limited in the vectors that we can create? What happens when two vectors exist in the same direction, or exist on the same line? The combination of those vectors is also stuck on the same line, limiting our span to jsut that line. Now matter how you scale itm, the resulting sum vector is also stuck on the same line. 

This makes them *Linearly Dependent*. In a three dimensional space, when we have a lienarly depdent set of vectors, we often get stuck on a plane in a smaller numer of dimensions. 

Why do we care whether two vectors are linearly dependent or independent? A lost of problesm become difficult or unsolveable when they are linearly depdendent.

## Linear Transformations

This concept of adding two vectors with fixed direction, but scaling them to get different combined vectors is hugely important. This combined vector, except in cases of linear dependence, can point in any direction.  and have any length we choose. This sets up an intuition for linear transformations where we use a vector to transform another vector in a function-like manner. 

### Basis Vectors

Imagine we have two simple vectors $\widehat{i}$ and $\hat{j}$. These are known as *basis vectors*, which are used to describe transformations on other vectors. They typically have a length of 1 and point in perpendicular positive directions.

Think of basis vectors as building blocks to build or transform any vector. Our basis vector is expressed in a 2 x 2 matrix, where the first column is $\hat{i}$ and the second column is $\hat{j}$. 

$\hat{i} \quad = \quad \begin{bmatrix} 1 \\ 0 \end{bmatrix}$

$\hat{j} \quad = \quad \begin{bmatrix} 0 \\ 1 \end{bmatrix}$

$\text{basis} \quad = \quad \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

a matrix is a collection of vectors that can have multiple rows and coloumns and is a convenient way of packaging data. We can use $\hat{i}$ and $\hat{j}$ to create any vector we want by scaling and adding them.

I want $\vec{v}$ to land at [3,2]. What happens to $\vec{v}$ if we stretch $\hat{i}$ by a factor of 3 and $\hat{j}$ by a factor of 2? First we scale individually:

$3\hat{i} \quad = \quad 3\begin{bmatrix} 1 \\ 0 \end{bmatrix} \quad = \quad \begin{bmatrix} 3 \\ 0 \end{bmatrix}$

$2\hat{j} \quad = \quad 2\begin{bmatrix} 0 \\ 1 \end{bmatrix} \quad = \quad \begin{bmatrix} 0 \\ 2 \end{bmatrix}$

If we stretched space in these two directions, what does this do to $\vec{v}$? It will stretch with $\hat{i}$ and $\hat{j}$. This is known as a *linear transformation*, where we transform a vector with stretching, squishing, sheering, or rotating by tracking basis vector movements. 

Recall that $\vec{v}$ is composed of adding $\hat{i}$ and $\hat{j}$, so we simply take the stretched $\hat{i}$ and $\hat{j}$ and add them together to see where vector $\vec{v}$ has landed:

$\vec{v}_{new} \quad = \quad \begin{bmatrix} 3 \\ 0 \end{bmatrix} + \begin{bmatrix} 0 \\ 2 \end{bmatrix} \quad = \quad \begin{bmatrix} 3 \\ 2 \end{bmatrix}$

Generally, with linear transformations there are four movements you can achieve: *Scale, Rotate, Shear, Inversion*

- Scaling a vector will stretch or squeeze it
- Rotations will turn the vector space
- Inversions will flip the vector space so that $\hat{i}$ and $\hat{j}$ swap respective places. 
- A shear displaces each point in a fixed direction proportionally to its distance to a given line parallel to that direction.

You cannot have transformations that are nonlinear, resulting in curvy or squiggly transformations that are no longer in a straight line. 

## Matrix Vector Multiplication

This concept of tracking where $\hat{i}$ and $\hat{j}$ land after a transformation is important because it allows us not just to create vectors, but also to transform existing vectors.

The formula to transform a vector $\vec{v}$ given basis vectors $\hat{i}$ and $\hat{j}$ packaged as a matrix is:

$\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} \quad = \quad \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

$\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} \quad = \quad \begin{bmatrix} ax + by \\ cx + dy \end{bmatrix}$

$\hat{i}$ is the first column $[a , c]$ and $\hat{j}$ is the column $[b, d]$. We package both of these basis vectors as a matrix; which, again, is a collection of vectors expressed as a grid of snumbers in two ore more directions. This transformation of a vector by applying basis vectors is known as *matrix vector multiplication* This formula is a shortcut fo scaling and adding $\hat{i}$ and $\hat{j}$ just like we did earlier adding two vectors, and applying the transformation to any vector $\vec{v}$. 

In effect, a matrix really is a transformation expressed as basis vectors. 

To execute this in numpy we need to declare our basis vectors as a matrix and then apply it to vector $\vec{v}$ using the `dot()` operator. The `dot()` operator will perform this caling and addition between our matrix and vector. This is known as the *dot product*.

In [10]:
# compose basis matrix with i-hat and j-hat
basis = np.array([[3, 0], [0, 2]])

#declare vector v
v = np.array([1, 1])

#create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[3 2]


When thinking in terms of basis vectors, I prefer to break out the basis vectors and then compose them together into a matrix. Just note you will need to *traanspose*, or swap the columns and rows. This is because NumPy's `array()` function will do the opposite orientation we want. Populating each vector as a row rather than a column.

In [11]:
# transposition

#declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])

#compose basis matrix using i-hat and j-hat, also need to transpose into columns
basis = np.array([i_hat, j_hat]).transpose()

#declare vector v
v = array([1, 1])

#create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[2 3]


Here's another example. Let's start with vector $\vec{v}$ being [2,1] and $\hat{i}$ and $\hat{j}$ start at [1, 0] and [0, 1], respectively. We then transform $\hat{i}$ and $\hat{j} to [2, 0] and [0, 3]. 

What happens to vector $\vec{v}$? Working this out mathematically by hand using our formula, we get this:

$\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} \quad = \quad \begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

$\begin{bmatrix} x_{new} \\ y_{new} \end{bmatrix} \quad = \quad \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix} \begin{bmatrix} 2 \\ 1 \end{bmatrix} \quad = \quad \begin{bmatrix} (2)(2) + (0)(1) \\ (2)(0) + (3)(1) \end{bmatrix} \quad = \quad \begin{bmatrix} 4 \\ 3 \end{bmatrix}$

This solution using NumPy:

In [12]:
#declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])

#compose basis matrix using i-hat and j-hat, also need to transpose into columns
basis = np.array([i_hat, j_hat]).transpose()

# declare vector v 0
v = np.array([2, 1])

# create new vector by transforming v with dot product
new_v = basis.dot(v)

print(new_v)

[4 3]


The vector $\vec{v}$ now lands at [4,3]. 

## Matrix Multiplication

We learned how to multiply a vector and amatrix, but what exactly does multiplying two matrices accomplish? Think of *matrix multiplication* as applying multiple transformations to a vector space. Each transformation is like a function, where we apply the innermost first and then apply each subsequent transformation outward.

here is how we apply a rotation and then a shear to any vector $\vec{v}$ with value $[v, y]$:

$\begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

We can actually consolidate these two transformations by using this formula. Applying one transformation onto the last. You multiply and add each row from the first matrix to each respective column of the second matrix, in an "over-and-down"! "over-and-down"! pattern:

$\begin{bmatrix} a & b \\ c & d \end{bmatrix} \begin{bmatrix} e & f \\ g & h \end{bmatrix} \quad = \quad \begin{bmatrix} ae + bg & af + bh \\ ce + dg & cf + dh \end{bmatrix}$

So we can actually consolidate these two separate transformations (rotation and shear) into a single transformation:

$\begin{bmatrix} 1 & 1 \\ 0 & 1 \end{bmatrix} \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

$= \quad \begin{bmatrix} (1)(0) + (1)(1) & (-1)(1) + (1)(0) \\ (0)(0) + (1)(1) & (0)(-1) + (1)(0) + (1) \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

$= \quad \begin{bmatrix} 1 & -1 \\ 1 & 0 \end{bmatrix} \begin{bmatrix} x \\ y \end{bmatrix}$

To execute this in python using numpy, you can combine the two matrices simply using the `matmul()` or `@` opearator. We will then turn around and use this consolidated transformation and apply it to a vector [1,2].  

In [13]:
#transformation 1
i_hat1 = np.array([0, 1])
j_hat1 = np.array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

#transformation 2
i_hat2 = np.array([1, 0])
j_hat2 = np.array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

#combine transformations
combined = transform2 @ transform1

#test
print('COMBINED MATRIX:\n {}'.format(combined))

v = np.array([1, 2])
print(combined.dot(v))

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


Note that the order of the transformation matters!! If we apply `transformation1` on `transformation2`, we get a different result of [-2, 3]. So matrix dot products are not commutative, meaning you cannot flip the order and expect the same result.

## Determinants
When we perform linear transformations, we sometimes "expand" or "squish" space and the degreee this happens can be helpful:

In [14]:
# a negative determinant
from numpy.linalg import det

i_hat = np.array([-2, 1])
j_hat = np.array([1, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


Because this determinant is negative, we suiqkcly see that the orientation has flipped. But by far the most critical piece of information the determinatn tells you is whether the transformation is linearly dependent. 

> If you have a determinant of 0, that means all of the space ahs been squished into a lesser dimension.

In [17]:
# a determinant of 0
i_hat = np.array([3, -1.5])
j_hat = np.array([-2, 1])
basis = array([i_hat, j_hat]).transpose()
determinant = det(basis)
print(determinant)

0.0


So, testing for a 0 determinant is highly helpful to determine if a transformation has linear dependence. When you encounter this you will likley find a difficult or unsolvable problem on your hands.

## Special Types of Matrices
There are a few notable cases of matrices that we should cover.

### Square Matrix 
The *square matrix* is a matrix that has an equal number of rows and columns:

$\begin{bmatrix} 4 & 2 & 7 \\ 5 & 1 & 9 \\ 4 & 0 & 1 \end{bmatrix}$

They are primarily used to represent linear transformations and are a requriement of many operations like eigendecomposition. 

### Identity Matrix
The *identity matrix* is a quare matrix that has a diagonal of 1s while the other values are 0:

$\begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

Whats the big deal with identity matrices? Well, when you have an idneity matrix, you essentially have undone a transformation and now found your starting basis vectors. This will play a big role in solving systems of equations.

### Inverse Matrix
An *inverse matrix* is a matrix that undoes the transformation of another matrix Let's say I have matrix A:

$\begin{bmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6 \end{bmatrix}$

The inverse of matrix $A$ is called $A^{-1}$. The inverse of matrix $A$ is:

$\begin{bmatrix} -\frac{1}{2} & 0 & \frac{1}{3} \\ 5.5 & -2 & -\frac{4}{3} \\ -2 & 1 & \frac{1}{3} \end{bmatrix}$

When we perform matrix multiplication between $A^{-1}$ and $A$, we end up with an identity matrix.

$\begin{bmatrix} -\frac{1}{2} & 0 & \frac{1}{3} \\ 5.5 & -2 & -\frac{4}{3} \\ -2 & 1 & \frac{1}{3} \end{bmatrix} \begin{bmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6 \end{bmatrix} \quad = \quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

### Diagonal Matrix 
Similar to the idneity matrix is the *diagonal matrix*, which has a diagonal of nonzero values while the rest of the values are 0. Diagonal matrices are desirable in certain computtion because they represent simple sclaras being applied to a vector space. It shows up in some linear algebra operations

$\begin{bmatrix} 4 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 5 \end{bmatrix}$

### Triangular Matrix 

Similar to the diagonal matrix is the *triangular matrix, which has a diagonal of nonzero values in fromt of a triangle of values, while the rest of the values are 0.

$\begin{bmatrix} 4 & 2 & 9 \\ 0 & 1 & 6 \\ 0 & 0 & 5 \end{bmatrix}$

Triangular matrices are desirable in many numerical anlysis tasks, because they are typically easier to solve in systems of equations. They also show up in certain decomposition tasks like LU Decomposition.

### Sparse Matrix
Occasionally, you will run into matrices that are mostly zeroes and have very few non-zero elements. These are called *sparse matrices*. From a computing standpoint, they create opportunities to create efficiencies. If a matrix has mostly 0s, a sparse matrix implementation will not wasted space storing a bunch of 0s, and instead only track the cells that are non-zero.

$\text{sparse} \quad = \quad \begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}$

When you have large matrices that are sparse, you might explicitly use a sparse function to create your matrix.
 


## Systems of Equations and Inverse Matrices

One of the basic use cases for linear algebra is solving systems of linear equations. It is also a good application to learn about inverse matrices. Let's say you are provided with the following equations and need to solve for $x$, $y$, and $z$:

$4x + 2y + 4z \quad = \quad 44$

$5x + 3y + 7z \quad = \quad 56$

$9x + 3y + 6z \quad = \quad 72$

You can try manually experimenting with different algebraic operations to isolate the three variables, but if you want a computre to solve it you will need to express the problem in terms of matrices shown next:
- Extract the coefficients into matrix $A$
- The values on the right side into matrix $B$
- The unknown variables into matrix $X$

$A \quad = \quad \begin{bmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6 \end{bmatrix}$

$B \quad = \quad \begin{bmatrix} 44 \\ 56 \\ 72 \end{bmatrix}$

$X \quad = \quad \begin{bmatrix} x \\ y \\ z \end{bmatrix}$

The function for a linear system of equations is $AX = B$. We need to tranform matrix $A$ with some other matrix $X$ that will result in matrix $B$.

$AX \quad = \quad B$

$\begin{bmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6 \end{bmatrix} \cdot \begin{bmatrix} x \\ y \\ z \end{bmatrix} \quad = \quad \begin{bmatrix} 44 \\ 56 \\ 72 \end{bmatrix}$

We need to "undo" $A$ so that we can isolate $X$ and get the values for $x$, $y$, and $z$. The way you undo $A$ is to take the inverse of $A$, (denoted $A^{-1}$) and apply it to $A$ via matrix multiplication. We can express this algebraically:

$AX \quad = \quad B$

$A^{-1}AX \quad = \quad A^{-1}B$

$X \quad = \quad A^{-1}B$

To calculate the inverse of $A$, we probably use a computre rather than searching for solutions using gaussian elimination Here is the inverse of matrix $A$:

$\begin{bmatrix} -\frac{1}{2} & 0 & \frac{1}{3} \\ 5.5 & -2 & -\frac{4}{3} \\ -2 & 1 & \frac{1}{3} \end{bmatrix}$

Note when we matrix multiply $A^{-1}$ against $A$  it will create an identity matrix, a matrix of all zeroes except for 1s in the diagonal. The idnetity matrix is the linear algebra equivalent of multiplying by 1,, meaning it essentially has no effect and will effectively isolate values for $x$, $y$, and $z$:

$A^{-1} \quad = \quad \begin{bmatrix} -\frac{1}{2} & 0 & \frac{1}{3} \\ 5.5 & -2 & -\frac{4}{3} \\ -2 & 1 & \frac{1}{3} \end{bmatrix}$

$A \quad = \quad \begin{bmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6 \end{bmatrix}$

$A^{-1}A \quad = \quad \begin{bmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

To see this identity matrix in action using python, you will want to use sympy instead of numpy. The floating point decimals in NumPy will not make the identiy matrix as obvious, but doing it symbolically we will see a clean, symbolic output. Note that to do matrix multiplication in SymPy we use the asterisk `*` rather than `@`.



In [18]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([[4, 2, 4], [5, 3, 7], [9, 3, 6]])

#dot product between A and its inverse, will produce identity function
inverse = A.inv()
identity = inverse * A

print("INVERSE: {}".format(inverse))

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])


In [19]:
print("IDENTITY: {}".format(identity))

IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


Let's do the same calculation in numpy:

In [20]:
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = np.array([[4, 2, 4], [5, 3, 7], [9, 3, 6]])
B = np.array([44, 56, 72])
X = inv(A).dot(B)

print(X)

[ 2. 34. -8.]


So $x = 2$, $y = 34$, and $z = -8$

The next example shows the full solution in SymPy:

In [22]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([[4, 2, 4], [5, 3, 7], [9, 3, 6]])
B = Matrix([44, 56, 72])
X = A.inv() * B
print(X)

Matrix([[2], [34], [-8]])


In practicality, you should rarely find it necessary to calculate inverse matrices by hand and can have a computer do it for you. But if you have a need or are curious you need to learn about Gaussian Elimination. PatrickJMT on YOutube has a numbewr of videso demonstrating Gaussian Elimination.

## Eigenvectors and Eigenvalues

*Matrix Decomposition* is breaking up a matrix into its basic components, much like factoring numbers (e.g., 10 and be factored to 2 x 5). Matrix decomposition is helpful for tasks like finding inverse matrices and calculating determinants, as well as linear regression. There are many ways to decompose a matrix depending on your task. 

A common method is called *Eigendecomposition*, which is often used for machine learning and principal component analysis. Eigendocmposition is helpful for breaking up a matrix into components that are easier to work with in differnt machine learnign tasks. It also only works on square matrices. In eigendecomposition there are two components:
- The eigenvalues denoted by lambda $\lambda$
- eigenvector $v$

If we have a square matrix $A$, it has the following eigenvalue equation:

$Av \quad = \quad \lambda v$

If $A$ is the original matrix, it is composed of eigenvector $v$ and eigenvalue $\lambda$. There is one eigenvector and eigenvalue for each dimension of the parent matrix, and not all matrices can be decomposed into an eigenvector and eigenvalue. Somtimes complex (imaginary) values will even result. 

This example is how we calculate eigenvectors and eigenvalues in NumPy for a given matrix $A$.

In [26]:
# Performing eigendecomposition in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([[1, 2],[3, 4]])
eigenvals, eigenvecs = eig(A)

In [27]:
print("EIGENVALUES")
print(eigenvals)

EIGENVALUES
[-0.37228132  5.37228132]


In [28]:
print("EIGENVECTORS")
print(eigenvecs)

EIGENVECTORS
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


So how do we rebuild matrix $A$ from the eigenvectors and eigenvalues?

Recall the formula: 

$Av \quad = \quad \lambda v$

We need to make a few tweaks to the formula to reconstruct $A$:

$A \quad = \quad Q\Lambda A^{-1}$

In this new formula, $Q$ is the eigenvectors, $\Lambda$ is the eigenvalues in diagonal form, and $Q^{-1}$ is the inverse matrix of $Q$. Diagonal form means the vector is padded into a matrix of zeroes and occupies the diagonal line in a similar pattern to an identity matrix. 

The below example brings this concept full circle in Python, starting with decomposing the matrix, and then recomposing it.

In [29]:
# Decomposing and recomposing a matrix in NumPy
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([[1, 2], [4, 5]])
eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)

EIGENVALUES
[-0.46410162  6.46410162]


In [30]:
print("EIGENVECTORS")
print(eigenvecs)

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


In [31]:
print("REBUILD MATRIX")
Q = eigenvecs
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R
print(B) #prints the matrix we started with

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]
